//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team2LibraryProject_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int GenreID { get; set; }
        public string Genre1 { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
