//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team2LibraryProject_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.Loans = new HashSet<Loan>();
        }
    
        public int ItemID { get; set; }
        public float ItemPrice { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string ISBN { get; set; }
        public bool OnShelf { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ICollection<Loan> Loans { get; set; }
    }
}
