//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team2LibraryProject_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLoansView
    {
        public int LoanID { get; set; }
        public int ItemID { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public int CardNo { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public float Fines { get; set; }
        public bool FinesPaid { get; set; }
    }
}
