//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team2LibraryProject_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberReviewsView
    {
        public string FName { get; set; }
        public string LName { get; set; }
        public int CardNo { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public float Rating { get; set; }
        public string ReviewText { get; set; }
        public int ReviewID { get; set; }
    }
}
