//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team2Library_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string ISBN { get; set; }
        public string Author_FName { get; set; }
        public string Author_LName { get; set; }
        public string Publisher { get; set; }
        public int NumOfPages { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public int Genre { get; set; }
        public int Language { get; set; }
        public Nullable<float> Rating { get; set; }
        public string Synopsis { get; set; }
        public int Shelf { get; set; }
    }
}
