//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team2Library_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ItemID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> DvdID { get; set; }
        public float ItemPrice { get; set; }
    }
}
