// <auto-generated />
namespace Team2LibraryProject_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MemberType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberType));
        
        string IMigrationMetadata.Id
        {
            get { return "201504122037091_MemberType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
